using System.Net;

namespace FieldOps.Domain.Notifications;

// Append-only: audit records are written once and never updated, so this
// entity intentionally exposes no mutators beyond Create. entity_type and
// entity_id stay untyped (no FK) so an audit record can reference any
// domain entity without coupling AuditLog to every aggregate in the system.
public sealed class AuditLog
{
    private AuditLog()
    {
    }

    private AuditLog(
        Guid organizationId,
        string action,
        string entityType)
    {
        OrganizationId = organizationId;
        Action = action;
        EntityType = entityType;
        Metadata = "{}";
        OccurredAt = DateTimeOffset.UtcNow;
    }

    // bigserial: generated by the database identity column, never assigned
    // by the domain.
    public long Id { get; private set; }

    public Guid OrganizationId { get; private set; }

    public Guid? ActorUserId { get; private set; }

    public string Action { get; private set; } = string.Empty;

    public string EntityType { get; private set; } = string.Empty;

    public Guid? EntityId { get; private set; }

    public Guid? BranchId { get; private set; }

    public string? BeforeData { get; private set; }

    public string? AfterData { get; private set; }

    public string Metadata { get; private set; } = "{}";

    public IPAddress? IpAddress { get; private set; }

    public DateTimeOffset OccurredAt { get; private set; }

    public static AuditLog Create(
        Guid organizationId,
        string action,
        string entityType,
        Guid? actorUserId = null,
        Guid? entityId = null,
        Guid? branchId = null)
    {
        if (organizationId == Guid.Empty)
        {
            throw new ArgumentException(
                "Organization id is required.",
                nameof(organizationId));
        }

        if (string.IsNullOrWhiteSpace(action))
        {
            throw new ArgumentException(
                "Audit action is required.",
                nameof(action));
        }

        if (string.IsNullOrWhiteSpace(entityType))
        {
            throw new ArgumentException(
                "Audit entity type is required.",
                nameof(entityType));
        }

        return new AuditLog(
            organizationId,
            action.Trim(),
            entityType.Trim())
        {
            ActorUserId = actorUserId,
            EntityId = entityId,
            BranchId = branchId,
        };
    }
}
