using System.Globalization;
using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;
using FieldOps.IntegrationTests.Api;
using FieldOps.IntegrationTests.BillingReview;
using FieldOps.IntegrationTests.CompanySettings;
using FieldOps.IntegrationTests.ServiceRequests;
using FieldOps.IntegrationTests.Sessions;

namespace FieldOps.IntegrationTests.InvoiceDelivery;

/// <summary>A draft invoice generated by the completed jobs review, with the job it came from.</summary>
internal sealed record DraftInvoice(Guid Id, string Number, BillingJob Job);

/// <summary>Requests, seeds and database probes of the invoice draft delivery integration tests.</summary>
internal static partial class InvoiceApi
{
    public const string Message = "Thanks for choosing us. Your invoice is ready.";

    [GeneratedRegex("/invoices/view#token=(?<token>[A-Za-z0-9_-]{43})", RegexOptions.CultureInvariant)]
    private static partial Regex LinkPattern();

    public static string Path(Guid id, string suffix = "") => $"/invoices/{id}{suffix}";

    public static string Stamp() => DateTimeOffset.UtcNow.ToString("O", CultureInfo.InvariantCulture);

    public static JsonObject Body(
        string? terms = "net_15", string? recipient = "carla@example.com", string? message = Message, string? updatedAt = null) =>
        new()
        {
            ["paymentTerms"] = terms,
            ["recipientEmail"] = recipient,
            ["message"] = message,
            ["updatedAt"] = updatedAt,
        };

    public static JsonObject Resend(string? updatedAt) => new() { ["updatedAt"] = updatedAt };

    /// <summary>Seeds a ready job and generates its draft invoice through the real review endpoint.</summary>
    public static async Task<DraftInvoice> GenerateDraftAsync(
        this CompanySettingsDatabaseFixture db,
        Func<HttpMethod, string, JsonObject?, Task<HttpResponseMessage>> send,
        RequestWorld world,
        Guid user,
        JobSpec? spec = null,
        string terms = "net_15")
    {
        var job = await db.SeedJobAsync(world, user, spec);
        var created = await BillingSeed.ReadAsync(
            await send(HttpMethod.Post, BillingSeed.Detail(job.Order) + "/invoice", BillingSeed.InvoiceBody(BillingSeed.Today("UTC"), terms, acknowledge: true)),
            HttpStatusCode.Created);

        return new DraftInvoice(created["invoice"]!["id"]!.GetValue<Guid>(), created["invoice"]!["number"]!.GetValue<string>(), job);
    }

    public static Task<DraftInvoice> GenerateDraftAsync(
        this CompanySettingsDatabaseFixture db, RequestsHost host, string cookie, RequestWorld world, Guid user, JobSpec? spec = null, string terms = "net_15") =>
        db.GenerateDraftAsync((method, path, body) => host.SendAsync(method, path, cookie, body), world, user, spec, terms);

    public static async Task<JsonNode> DetailAsync(RequestsHost host, string cookie, Guid id) =>
        await BillingSeed.ReadAsync(await host.SendAsync(HttpMethod.Get, Path(id), cookie));

    /// <summary>The raw token of the link in the email (the only place it exists).</summary>
    public static string TokenOf(FieldOps.Application.Features.Email.EmailMessage message)
    {
        var match = LinkPattern().Match(message.TextBody);
        Assert.True(match.Success, "The email has no invoice link.");

        return match.Groups["token"].Value;
    }

    public static string Hash(string raw) => Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(raw)));

    public static string NewToken() =>
        Convert.ToBase64String(RandomNumberGenerator.GetBytes(32)).TrimEnd('=').Replace('+', '-').Replace('/', '_');

    public static async Task<HttpResponseMessage> PublicAsync(HttpClient client, string action, string? token, string? ip = null)
    {
        var request = new HttpRequestMessage(HttpMethod.Post, $"/public/invoice-links/{action}")
        {
            Content = new StringContent(new JsonObject { ["token"] = token }.ToJsonString(), Encoding.UTF8, "application/json"),
        };
        request.Headers.Add(TestClientIpStartupFilter.HeaderName, ip ?? SessionApi.NewClientIp());

        return await client.SendAsync(request);
    }

    /// <summary>Everything a rejected, unauthorized or public request must leave untouched.</summary>
    public static Task<string> StateAsync(this CompanySettingsDatabaseFixture db, Guid invoice) =>
        db.ScalarAsync<string>(
            """
            SELECT i.status::text || '|' || i.updated_at::text || '|' || COALESCE(i.recipient_email, '-') || '|' || COALESCE(i.delivery_message, '-')
                || '|' || COALESCE(i.payment_terms, '-') || '|' || COALESCE(i.due_date::text, '-') || '|' || COALESCE(i.sent_at::text, '-')
                || '|' || COALESCE(i.customer_snapshot::text, '-')
                || '|' || (SELECT COUNT(*) FROM invoice_access_tokens WHERE invoice_id = i.id)
                || '|' || (SELECT COUNT(*) FROM audit_logs WHERE entity_id = i.id)
            FROM invoices i WHERE i.id = @i
            """,
            ("i", invoice));

    public static Task<List<string>> AuditActionsAsync(this CompanySettingsDatabaseFixture db, Guid invoice) =>
        db.TextsAsync("SELECT action FROM audit_logs WHERE entity_id = @i ORDER BY id", ("i", invoice));

    /// <summary>Every audit value of the invoice as one text, to prove what it never contains.</summary>
    public static async Task<string> AuditTextAsync(this CompanySettingsDatabaseFixture db, Guid invoice) =>
        string.Join(
            '\n',
            await db.TextsAsync(
                "SELECT COALESCE(before_data::text, '') || COALESCE(after_data::text, '') || metadata::text || COALESCE(ip_address::text, '') FROM audit_logs WHERE entity_id = @i",
                ("i", invoice)));

    public static Task<long> ActiveTokensAsync(this CompanySettingsDatabaseFixture db, Guid invoice) =>
        db.CountAsync("invoice_access_tokens", "invoice_id = @i AND revoked_at IS NULL", ("i", invoice));

    public static Task InsertTokenAsync(
        this CompanySettingsDatabaseFixture db, Guid org, Guid invoice, Guid user, string raw, bool expired = false) =>
        db.ExecuteAsync(
            """
            INSERT INTO invoice_access_tokens (organization_id, invoice_id, token_hash, created_at, expires_at, created_by_user_id)
            VALUES (@o, @i, @h, CASE WHEN @expired THEN now() - interval '3 days' ELSE now() END,
                CASE WHEN @expired THEN now() - interval '1 day' ELSE now() + interval '30 days' END, @u)
            """,
            ("o", org),
            ("i", invoice),
            ("h", Hash(raw)),
            ("expired", expired),
            ("u", user));

    public static async Task<string> WithoutTraceAsync(HttpResponseMessage response)
    {
        var problem = (JsonObject)JsonNode.Parse(await response.Content.ReadAsStringAsync())!;
        problem.Remove("traceId");

        return problem.ToJsonString();
    }
}
